#!/bin/sh
#
# Set your outgoing interfaces and upload rates (in Mbit/s) here

DEVS="vlan1088"
# tun1 vlan16"
RATEUP=20
PRIMRATE=15
SECMRATE=5

# Which ports should be prioritized  (may be empty "")
TCPPORTS=""
#1501:1550"

# Which servers should be prioritized (may be empty "")
SERVERIPS="85.89.230.193 85.89.230.216"


# end of configuration options

######################
# show status and exit
######################

if [ "$1" = "status" ]
then
    for DEV in $DEVS; do
	echo ""
	echo "-- $DEV --"
	echo ""

        echo "[qdisc]"
        tc -s qdisc show dev $DEV

        echo ""
        echo "[class]"
        tc -s class show dev $DEV

        echo ""
        echo "[filter]"
        tc -s filter show dev $DEV

        echo ""
        echo "[iptables]"
        iptables -t mangle -L DSMSHAPER -v -x 2> /dev/null
    done
    exit
fi

######################
# default: start it  #
######################

for DEV in $DEVS; do
    # Reset everything to a known state (cleared)
    tc qdisc del dev $DEV root    2> /dev/null > /dev/null

    # Flush and delete tables
    iptables -t mangle --delete POSTROUTING -o $DEV -j DSMSHAPER 2> /dev/null > /dev/null
done
iptables -t mangle --flush        DSMSHAPER 2> /dev/null > /dev/null
iptables -t mangle --delete-chain DSMSHAPER 2> /dev/null > /dev/null

######################
# stop it and exit
######################

if [ "$1" = "stop" ]
then
        echo "Shaping removed on ${DEVS}."
        exit
fi

######################
# set up shaping
######################

# add DSMSHAPER chain to the mangle table in iptables
iptables -t mangle --new-chain DSMSHAPER

for DEV in $DEVS; do
    # add HFSC root qdisc
    tc qdisc add dev $DEV root handle 1: hfsc default 10

    # add main rate limit class
    tc class add dev $DEV parent 1: classid 1:1 hfsc sc rate ${RATEUP}mbit ul rate ${RATEUP}mbit

    # keep it simple: two classes only
    tc class add dev $DEV parent 1:1 classid 1:10 hfsc sc rate ${SECMRATE}mbit ul rate ${RATEUP}mbit
    tc class add dev $DEV parent 1:1 classid 1:11 hfsc sc rate ${PRIMRATE}mbit ul rate ${RATEUP}mbit

    # add DSMSHAPER chain to the mangle table in iptables
    iptables -t mangle --insert POSTROUTING -o $DEV -j DSMSHAPER

    # Filter for packets
    tc filter add dev $DEV parent 1: prio 1 protocol ip handle 1 fw flowid 1:11
done

# ports as defined above
for port in $TCPPORTS
do
        iptables -t mangle -A DSMSHAPER -p tcp --sport $port -j MARK --set-mark 1
        iptables -t mangle -A DSMSHAPER -p tcp --dport $port -j MARK --set-mark 1
done

# IPs as defined above
for ip in $SERVERIPS
do
        iptables -t mangle -A DSMSHAPER --src $ip -j MARK --set-mark 1
        iptables -t mangle -A DSMSHAPER --dst $ip -j MARK --set-mark 1
done



echo DSMSHAPER started on $DEVS with ${RATEUP}mbit/s upload rate.

echo -n "QoS activated for ports: "
for port in $TCPPORTS
do
        echo -n " $port"
done
echo "."

echo -n "QoS activated for ip#  : "
for ip in $SERVERIPS
do
        echo -n " $ip"
done
echo "."

#end